version: '3'
services:
  web: 
    image: ntpykt22/demo:2.0
    build: 
      context: ./nginx 
      dockerfile: dockerfile
    container_name: nginx-demo
    ports:
       - 7777:80
# Postgres
  database:
    image: postgres-demo
    build:
      context: ./postgres
      dockerfile: dockerfile
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
#Javascirpt
  backend:
    image: backend:1.0
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend-demo
    ports:
      - 3000:3000
    environment:
      DB_HOST: database
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres

  frontend:
    image: frontend:1.0
    build:
      context: frontend
      dockerfile: dockerfile
    container_name: frontend-demo
    ports:
      - 8888:80

